jobs:
- job: Windows
  pool:
    vmImage: windows-2019
  steps:
  - bash: |
      curl -OsSL https://testspace-client.s3.amazonaws.com/testspace-windows.zip
      unzip -q testspace-windows.zip
      ./testspace config url samples.testspace.com
      ./testspace -v
    displayName: 'Setup'
  - task: NuGetCommand@2
    inputs:
      command: 'restore'
      restoreSolution: 'money\cs-money.sln'
  - task: VSBuild@1
    inputs:
      solution: 'money\cs-money.sln'
      vsVersion: '15.0' # Optional. Options: latest, 15.0, 14.0, 12.0, 11.0
      configuration: Debug
      msbuildArgs: '/p:runCodeAnalysis=true /p:codeanalysislogfile=..\analysis.xml'
  - script: |
      .\money\packages\OpenCover.4.7.1221\tools\OpenCover.Console -target:".\money\packages\NUnit.ConsoleRunner.3.16.3\tools\nunit3-console.exe" -targetargs:"money\bin\Debug\cs-money.dll" -output:"coverage.xml" -filter:"+[*]* -[*]*MoneyTest*" -register:user
    displayName: 'Test'
  - script: |
      testspace analysis.xml [Tests]TestResult.xml coverage.xml
    condition: always()
    displayName: 'Push'
