jobs:
- job: Windows
  pool:
    vmImage: 'vs2015-win2012r2'
  steps:
  - bash: |
      curl -OsSL https://testspace-client.s3.amazonaws.com/testspace-windows.zip
      unzip -q testspace-windows.zip
      testspace config url samples.testspace.com
      testspace -v
    displayName: 'Setup'
  - script: |
      nuget restore money/cs-money.sln
      msbuild money/cs-money.csproj /p:runCodeAnalysis=true /p:codeanalysislogfile=..\analysis.xml
    displayName: 'Build'
  - script: |
      .\money\packages\OpenCover.4.6.519\tools\OpenCover.Console -target:".\money\packages\NUnit.ConsoleRunner.3.4.1\tools\nunit3-console.exe" -targetargs:"money\bin\Debug\cs-money.dll" -output:"coverage.xml" -filter:"+[*]* -[*]*MoneyTest*" -register:user
    displayName: 'Test'
  - script: |
      testspace analysis.xml [Tests]TestResult.xml coverage.xml
    condition: always()
    displayName: 'Push'
